deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: monzurul/SampleApp_CodeDeploy_Travis
  bucket: code-deploy-application-demo
  region: ap-southeast-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: code-deploy-application-demo
  key: latest_master.zip
  bundle_type: zip
  application: CodeDeployApplicationDemo
  deployment_group: EC2Deploy
  region: ap-southeast-1
  on:
    branch: master
script:
  - zip -r latest_master *
  - mkdir -p dpl_cd_upload
  - mv latest_master.zip dpl_cd_upload/latest_master.zip
